development:
  password:
  theme_id:
  store: domain.myshopify.com
  ignore_files:
    - settings_data.json

production:
  password:
  theme_id:
  store: domain.myshopify.com
  ignore_files:
    - settings_data.json
